# http://search.cpan.org/dist/CPAN-Meta/lib/CPAN/Meta/Spec.pm
# http://module-build.sourceforge.net/META-spec-v1.4.html
name:         Module-Generic
version:      0.1
version_from: lib/Module/Generic.pm
author:       Jacques Deguest <jack@deguest.jp>
license:      perl
installdirs:  site
requires:
    Scalar::Util: 0
    Data::Dumper: 0
    Data::Printer: 0
    Devel::StackTrace: 0
    Class::Struct: 0
recommends:
    Text::Number: 0
    Number::Format: 0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 7.18
